#----- CONFIGURATION FILE FOR STAFF UTILITIES -----#
#----- CREATED BY TOMSTER09090 -----#
#----- ANY ISSUES CONTACT ME ON DISCORD: tomster#7341-----#

#----- CLEAR CHAT -----#
number-of-lines-to-clear: 50

#----- STAFF CHAT -----#
staff-chat-enabled: true
staff-chat-prefix-format: "&d[&5STAFF CHAT&d]&5 %name% &d↠"

#----- MANAGEMENT CHAT -----#
management-chat-enabled: true
management-chat-prefix-format: "&d[&5MANAGEMENT CHAT&d]&5 %name% &d↠"

#----- CHAT COOLDOWN -----#

time-in-seconds: 5
cooldown-message: "&cHey %player%! You're talking too fast! Please wait %seconds% before you can chat again."

#----- RESOURCE PACK -----#
#Set this option to false if you would like to allow your players to join your server without a resource pack.
force-resource-pack: true
console-notify-on-fail: false
#If set to true, this is where you should put your server resource pack for the plugin to attempt to download client-side.
resource-pack-link: "RESOURCE-PACK"

#----- DISCORD MINECRAFT CHAT INTEGRATION -----#

#Here is where you put your Discord Bot Token, as well as what you'd like the Activity status to say!
bot-token: "BOT TOKEN"
bot-activity: "BOT STATUS"

#This is where you put the server-id, and the channel name (For the bot to send the messages into)
guild-id: "GUILD ID"
text-channel-name: "CHANNEL-NAME"
discord-chat-to-minecraft: false